# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Area.create!(name: "Sarkhej")
Area.create!(name: "Vasna")
Area.create!(name: "Vejalpur 1")
Area.create!(name: "Vejalpur 2")
Area.create!(name: "Juhapura")
Area.create!(name: "Prahladnagar")
Area.create!(name: "Jodhpur")
Area.create!(name: "Vastrapur")
Area.create!(name: "Bodakdev")
Area.create!(name: "Bopal")
Area.create!(name: "Thaltej 1")
Area.create!(name: "Thaltej 2")
Area.create!(name: "Rannapark")
Area.create!(name: "Ghatlodia 1")
Area.create!(name: "Ghatlodia 2")
Area.create!(name: "Nirnay Nagar")
Area.create!(name: "Vadaj")
Area.create!(name: "Ranip 1")
Area.create!(name: "Ranip 2")
Area.create!(name: "Chandkheda")
Area.create!(name: "Motera")
Area.create!(name: "Nana Chiloda")
Area.create!(name: "Airport")
Area.create!(name: "Gandhinagar")
Area.create!(name: "Naroda")
Area.create!(name: "New Naroda")
Area.create!(name: "Bapunagar")
Area.create!(name: "Saraspur")
Area.create!(name: "Gomtipur")
Area.create!(name: "Gitamandir")
Area.create!(name: "Jamalpur")
Area.create!(name: "Dani Limda")
Area.create!(name: "Shah-aalam")
Area.create!(name: "Narol")
Area.create!(name: "Vatva")
Area.create!(name: "Isanpur")
Area.create!(name: "Rakhiyal")
Area.create!(name: "Krishnanagar")
Area.create!(name: "Odhav")
Area.create!(name: "Vastral")
Area.create!(name: "Nikol")
Area.create!(name: "Asarva")
Area.create!(name: "Maninagar")
Area.create!(name: "Paldi")
Area.create!(name: "Ellisbridge")
Area.create!(name: "Stadium")
Area.create!(name: "Ankur")
Area.create!(name: "Naranpura")
Area.create!(name: "Usmanpura")
Area.create!(name: "RTO")

suv = CarType.create!(name: "Sedan/SUV")
hatch = CarType.create!(name: "Hatchback")
small = CarType.create!(name: "Small")

Car.create!(name: "Swift Dzire", car_type_id: suv.id)
Car.create!(name: "Toyota Etios", car_type_id: suv.id)
Car.create!(name: "Hyundai Accent", car_type_id: suv.id)
Car.create!(name: "Mahindra KUV", car_type_id: suv.id)
Car.create!(name: "Tata Indigo", car_type_id: suv.id)
Car.create!(name: "Nissan Sunny", car_type_id: suv.id)
Car.create!(name: "Toyota Innova", car_type_id: suv.id)
Car.create!(name: "Maruti Ertiga", car_type_id: suv.id)
Car.create!(name: "Cheverolate Enjoy", car_type_id: suv.id)
Car.create!(name: "Hyundai Verna", car_type_id: suv.id)
Car.create!(name: "Honda City", car_type_id: suv.id)

Car.create!(name: "Hyundai I10", car_type_id: hatch.id)
Car.create!(name: "Hyundai I20", car_type_id: hatch.id)
Car.create!(name: "Swift", car_type_id: hatch.id)
Car.create!(name: "Dutson GO", car_type_id: hatch.id)
Car.create!(name: "Nissan Micra", car_type_id: hatch.id)
Car.create!(name: "Tata Indica", car_type_id: hatch.id)
Car.create!(name: "Maruti Ritz", car_type_id: hatch.id)

Car.create!(name: "Hyundai Santro", car_type_id: small.id)
Car.create!(name: "Maruti Alto", car_type_id: small.id)
Car.create!(name: "Tata Nano", car_type_id: small.id)
Car.create!(name: "Hyundai Eon", car_type_id: small.id)
Car.create!(name: "Maruti Eco", car_type_id: small.id)



RoleType.create!(name: "Franchise")
RoleType.create!(name: "Driver")
RoleType.create!(name: "User")